import { useMemo, useState } from "react";
import Badge from "../../components/Badge";
import Dropzone from "../../components/Dropzone";
import Icon from "../../components/Icon";
import Modal from "../../components/Modal";
import StatCard from "../../components/StatCard";
import { usePlatform } from "../../context/PlatformContext";

export default function Participants() {
  const { events, participants, addParticipants } = usePlatform();
  const [eventId,setEventId]=useState(1); const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [queued,setQueued]=useState(null);
  const visible=useMemo(()=>participants.filter((p)=>(eventId===0||p.eventId===eventId)&&`${p.name} ${p.email}`.toLowerCase().includes(query.toLowerCase())),[eventId,participants,query]);
  const verified=participants.filter(p=>p.enrollment==="verified").length; const invited=participants.filter(p=>p.enrollment==="invited").length;
  function importRows(){ if(!queued)return; addParticipants([{eventId,name:"New Participant",email:"participant@example.com"},{eventId,name:"Imported Attendee",email:"attendee@example.com"}]); setQueued(null); setOpen(false); }
  return <div className="page"><div className="page-head"><div><p className="eyebrow">Identity enrollment</p><h2>Participants</h2><p>Import attendees and track their secure, consent-based face enrollment.</p></div><button className="btn primary" onClick={()=>setOpen(true)}><Icon name="upload" size={16}/> Import participants</button></div><div className="stat-grid"><StatCard icon="students" label="Participants" value={participants.length} hint="Across all events"/><StatCard icon="mail" label="Invitations sent" value={participants.length} hint={`${invited} awaiting response`}/><StatCard icon="face" label="Faces submitted" value={verified} hint="Secure embeddings stored"/><StatCard icon="delivery" label="Galleries delivered" value={participants.filter(p=>p.delivery==="delivered").length} hint="Expiring private links"/></div><div className="toolbar"><select value={eventId} onChange={e=>setEventId(Number(e.target.value))}><option value="0">All events</option>{events.map(event=><option key={event.id} value={event.id}>{event.name}</option>)}</select><div className="toolbar-search"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email"/></div><span className="result-count">{visible.length} participants</span></div><div className="card table-wrap"><table><thead><tr><th>Participant</th><th>Event</th><th>Enrollment</th><th>Matches</th><th>Delivery</th><th>Imported</th><th/></tr></thead><tbody>{visible.map(p=><tr key={p.id}><td><div className="table-identity"><span className="person-avatar">{p.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><strong>{p.name}</strong><span>{p.email}</span></div></div></td><td>{events.find(e=>e.id===p.eventId)?.name??"Unknown"}</td><td><Badge status={p.enrollment}/></td><td>{p.matches}</td><td><Badge status={p.delivery}/></td><td>{p.uploadedAt}</td><td><button className="btn ghost small">•••</button></td></tr>)}</tbody></table></div><Modal open={open} onClose={()=>setOpen(false)} title="Import participants" description="CSV or Excel columns: Name, Email. Duplicates are validated before import." footer={<><button className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={!queued} onClick={importRows}>Validate & import</button></>}><div className="form-grid single"><div className="field"><label>Event</label><select value={eventId} onChange={e=>setEventId(Number(e.target.value))}>{events.map(event=><option key={event.id} value={event.id}>{event.name}</option>)}</select></div><Dropzone title="Add participant list" hint="Drop .csv, .xlsx or click to browse" accept=".csv,.xlsx,.xls" multiple={false} onFiles={files=>setQueued(files[0])}/>{queued?<div className="validation-summary"><Icon name="check" size={17}/><div><strong>{queued.name}</strong><p>Ready to validate email addresses and duplicates</p></div></div>:null}</div></Modal></div>;
}
